dist: xenial
language: python
python:
  - '3.7'
env:
  # https://github.com/travis-ci/travis-ci/issues/7940
  - BOTO_CONFIG=/dev/null
install:
  - make dep-dev
script:
  - make test
deploy:
  provider: script
  script: make deploy-prod-ci
  on: 
    branch: master