service: cfpland-telegram-bot

provider:
  name: aws
  region: eu-west-1
  runtime: python3.7
  environment: 
    DATABASE_URL: ${env:DATABASE_URL}
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    TELEGRAM_CFPLAND_CHANNEL: ${env:TELEGRAM_CFPLAND_CHANNEL}
  vpc:
    securityGroupIds:
      - sg-06ea07fa15e7613da
    subnetIds:
      - subnet-01595a21721d05a66
      - subnet-084fdc5a9a5fa3126
      - subnet-0e537c2e076614089

functions:
  parse: 
    handler: main.parse
    timeout: 30
    events:
      - schedule: cron(0 10 * * ? *)

  telegram_bot:
    handler: main.telegram_bot
    timeout: 30
    events:
      - http:
          path: /telegram_bot
          method: post

  send_telegram_messages_to_channel:
    handler: main.send_telegram_messages_to_channel
    timeout: 60
    events:
      - schedule: cron(0 11 * * ? *)

  set_telegram_webhook:
    handler: main.set_telegram_webhook

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: 'non-linux'